# Where to store the data.
storage:
  # The path of the database
  dbPath: "/data/db"

# Network interfaces
net:
  # Listen on localhost
  bindIp: 127.0.0.1
  # Listen on port 27017
  port: 27017

security:
  # Activate the authentification log into a database
  authorization: enabled
