services:
  nginx:
    build:
      context: ./services/nginx
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    secrets:
      - nginx.crt
      - nginx.key
    networks:
      - internal
    restart: "on-failure:5"
    depends_on:
      - webserv
  mongodb:
    build:
      context: ./services/mongo
    command: --config /etc/mongod.conf
    volumes:
      - mongodb:/data/db
    networks:
      - internal
    restart: "on-failure:5"
    environment:
      - MONGO_USER=$MONGO_USER
      - MONGO_PASS=$MONGO_PASS
      - MONGO_ADMIN_USER=$MONGO_ADMIN_USER
      - MONGO_ADMIN_PASS=$MONGO_ADMIN_PASS
  game:
    build:
      context: ./services/game_server
    networks:
      - internal
    restart: "on-failure:5"
    depends_on:
      - mongodb
    ports:
      - 0.0.0.0:3000:3000
  api:
    build:
      context: ./services/api
    networks:
      - internal
    restart: "on-failure:5"
    depends_on:
      - mongodb
    environment:
      - MONGO_USER=$MONGO_USER
      - MONGO_PASS=$MONGO_PASS
      - JWT_SECRET=$JWT_SECRET
      - JWT_HEADER_KEY=$JWT_HEADER_KEY
  webserv:
    build:
      context: ./services/web_server
    networks:
      - internal
    restart: "on-failure:5"
    depends_on:
      - mongodb
      - game
      - api

networks:
  internal:
    driver: bridge

secrets:
  nginx.key:
    file: ./cert/nginx.key
  nginx.crt:
    file: ./cert/nginx.crt

volumes:
  mongodb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/data/mongodb
    name: ft_transcendence_mongodb
