events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl;
        server_name trancendence.42.fr;

        ssl_certificate /run/secrets/nginx.crt;
        ssl_certificate_key /run/secrets/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        root /usr/share/nginx/html;
        index index.html;
        access_log  /var/log/nginx/access.log;

        location / {
            try_files $uri $uri/ /index.html$is_args$args;
        }

        location ~ /\. {
            deny all;
        }
    }

    server {
        listen 80;
        server_name trancendence.42.fr;
        return 301 https://$host$request_uri;
    }
}
