events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl;
        server_name trancendence.42.fr;

        ssl_certificate /run/secrets/nginx.crt;
        ssl_certificate_key /run/secrets/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            proxy_pass http://httpd:8080;
        }
    }

    server {
        listen 80;
        server_name trancendence.42.fr;
        return 301 https://$host$request_uri;
    }
}
