events {
    worker_connections 1024;
}
http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    keepalive_timeout 60;
    server {
        listen 443 ssl;
        server_name trancendence.42.fr;
        ssl_certificate /run/secrets/nginx.crt;
        ssl_certificate_key /run/secrets/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        error_page 404 /error/40x.html;
        root /usr/share/nginx/html;
        location ~* \.(css|js|jpg|jpeg|png|webp|gif|svg|ico|mp3)$ {
            access_log off;
            try_files $uri =404;
        }
        location = / {
            return 301 /hub/;
        }
        location = /hub/ {
            try_files /hub/page.html =404;
        }
        location /hub/ {
            try_files $uri =404;
        }
        location = /game {
            return 301 /game/;
        }
        location = /game/ {
            try_files /game/game.html =404;
        }
        location /game/ {
            try_files $uri =404;
        }
        location /ws/serv {
            proxy_pass http://game:3000;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_read_timeout 3600;
        }
        location /api {
            proxy_pass http://api:444;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
            proxy_read_timeout 3600;
        }
    }
    server {
        listen 80;
        server_name trancendence.42.fr;
        return 301 https://$host$request_uri;
    }
}